# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='sparsex',
  serialized_pb='\n\x0emessages.proto\x12\x07sparsex\"\xca\x02\n\x07Request\x12\'\n\x06\x61\x63tion\x18\x01 \x02(\x0e\x32\x17.sparsex.Request.Action\x12.\n\ninput_type\x18\x02 \x01(\x0e\x32\x1a.sparsex.Request.InputType\x12,\n\tdata_type\x18\x03 \x01(\x0e\x32\x19.sparsex.Request.DataType\x12\r\n\x05shape\x18\x04 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"G\n\x06\x41\x63tion\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08SHUTDOWN\x10\x01\x12\x10\n\x0cGET_FEATURES\x10\x02\x12\x13\n\x0fGET_PREDICTIONS\x10\x03\"\'\n\tInputType\x12\t\n\x05IMAGE\x10\x00\x12\x0f\n\x0bIMAGE_ARRAY\x10\x01\")\n\x08\x44\x61taType\x12\t\n\x05UINT8\x10\x00\x12\x07\n\x03INT\x10\x01\x12\t\n\x05\x46LOAT\x10\x02')



_REQUEST_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='sparsex.Request.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_FEATURES', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_PREDICTIONS', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=203,
  serialized_end=274,
)

_REQUEST_INPUTTYPE = _descriptor.EnumDescriptor(
  name='InputType',
  full_name='sparsex.Request.InputType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IMAGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMAGE_ARRAY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=276,
  serialized_end=315,
)

_REQUEST_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='sparsex.Request.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UINT8', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=317,
  serialized_end=358,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='sparsex.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='sparsex.Request.action', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_type', full_name='sparsex.Request.input_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='sparsex.Request.data_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='sparsex.Request.shape', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='sparsex.Request.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_ACTION,
    _REQUEST_INPUTTYPE,
    _REQUEST_DATATYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=358,
)

_REQUEST.fields_by_name['action'].enum_type = _REQUEST_ACTION
_REQUEST.fields_by_name['input_type'].enum_type = _REQUEST_INPUTTYPE
_REQUEST.fields_by_name['data_type'].enum_type = _REQUEST_DATATYPE
_REQUEST_ACTION.containing_type = _REQUEST;
_REQUEST_INPUTTYPE.containing_type = _REQUEST;
_REQUEST_DATATYPE.containing_type = _REQUEST;
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST

class Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST

  # @@protoc_insertion_point(class_scope:sparsex.Request)


# @@protoc_insertion_point(module_scope)
